name: Build & Push Docker Images

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
  workflow_run:
    workflows: ["laravel-test"]
    types:
      - completed

env:
  IMAGE_BACKEND: ${{ secrets.DOCKERHUB_USERNAME }}/event-backend
  IMAGE_FRONTEND: ${{ secrets.DOCKERHUB_USERNAME }}/event-frontend
  IMAGE_WEB: ${{ secrets.DOCKERHUB_USERNAME }}/event-web

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push backend image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./backend/docker/Dockerfile.php
          push: true
          tags: |
            ${{ env.IMAGE_BACKEND }}:latest
            ${{ env.IMAGE_BACKEND }}:${{ github.sha }}

      - name: Build & push frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_FRONTEND }}:latest
            ${{ env.IMAGE_FRONTEND }}:${{ github.sha }}

      - name: Build & push web image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./backend/docker/Dockerfile.nginx
          push: true
          tags: |
            ${{ env.IMAGE_WEB }}:latest
            ${{ env.IMAGE_WEB }}:${{ github.sha }}
