name: Laravel

on:
  workflow_dispatch:

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.3'
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: composer install --no-interaction --prefer-dist --optimize-autoloader
      
    - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
      run: php artisan test
